In [20]:
import pandas as pd
import numpy as np

In [6]:
transacoes = pd.read_csv('../data/transacoes.csv', sep=';')
transacoes.sample(10)

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
69435,34907f85-9f2e-43ed-9f1f-eaeae7b316fd,6582b314-afdb-47ef-88ff-a8d5c28fd4a7,2024-03-13 13:32:21.278,1,twitch
155021,75d3d4a0-de7d-4782-b0f5-98064ff4c154,752d53df-332a-4bcc-a673-3258583aa133,2025-09-19 12:31:07.238,1,twitch
17745,0d64aa05-4e7d-4291-a738-3184936d08b5,961622c3-3c29-4fa1-88d2-4f408d6d6ebb,2025-02-10 11:16:44.636,1,twitch
336213,ff5648c4-955a-4c56-8f86-2d78b87c46cb,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-05-16 13:38:31.530,1,twitch
185581,8d292b33-f98d-4aef-9ec1-a5749434c12c,5d69a93f-9ccb-41ca-a978-b984454054f5,2025-11-17 14:08:56.886,1,twitch
250045,bdf4c85e-f4de-4c0f-97a8-f4b7a38555b4,a6cc4ba8-3d4b-4f6e-8588-418c11ed095e,2024-02-14 11:56:19.203,1,twitch
315326,ef70b761-1a68-4b14-a2cc-2754b19e8ffb,14d59794-f89e-4623-b4ba-a6c4d76b3040,2024-05-24 11:55:14.790,1,twitch
74521,389172e8-674c-42f8-8c69-003b79d76599,5ed09fff-c0eb-48db-b6e3-20ef238e8b5c,2025-01-29 12:08:38.985,1,twitch
315178,ef54445d-0600-4e5f-a4ab-148a93272dc9,961622c3-3c29-4fa1-88d2-4f408d6d6ebb,2024-05-23 12:17:47.714,1,twitch
175597,85945f62-6255-474f-bcc9-4f086c177d86,961622c3-3c29-4fa1-88d2-4f408d6d6ebb,2025-07-17 12:04:45.847,1,twitch

In [8]:
transacoes.groupby(by=['IdCliente']).count()

,IdTransacao,DtCriacao,QtdePontos,DescSistemaOrigem
IdCliente,,,,
000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,2,2,2,2
000ff655-fa9f-4baa-a108-47f581ec52a1,512,512,512,512
001749bd-37b5-4b1e-8111-f9fbba90f530,1,1,1,1
0019bb9e-26d4-4ebf-8727-fc911ea28a92,2,2,2,2
0028dda2-334f-40bb-9582-475fb6719471,4,4,4,4
...,...,...,...,...
ff1ceaef-650c-422b-bdc3-6984e29e7aa5,15,15,15,15
ff2cabd3-3316-4b3f-8494-c25f95e90524,8,8,8,8
ff4909ad-4e52-4767-a6fc-0fbd76e37857,1,1,1,1
ff5d2399-6b53-49f0-b41e-fdaaa0da172a,385,385,385,385
fff7862d-4b2c-4140-a4c5-509b48ed31b4,1,1,1,1

In [11]:
transacoes.groupby(by='IdCliente', as_index=False)[['QtdePontos']].sum()

                                 IdCliente  QtdePontos
0     000dc0f6-e4f2-4a42-b8cd-b586ed1c709a           2
1     000ff655-fa9f-4baa-a108-47f581ec52a1       25086
2     001749bd-37b5-4b1e-8111-f9fbba90f530          50
3     0019bb9e-26d4-4ebf-8727-fc911ea28a92           2
4     0028dda2-334f-40bb-9582-475fb6719471        1100
...                                    ...         ...
3709  ff1ceaef-650c-422b-bdc3-6984e29e7aa5         162
3710  ff2cabd3-3316-4b3f-8494-c25f95e90524          57
3711  ff4909ad-4e52-4767-a6fc-0fbd76e37857          50
3712  ff5d2399-6b53-49f0-b41e-fdaaa0da172a        2021
3713  fff7862d-4b2c-4140-a4c5-509b48ed31b4        1000

[3714 rows x 2 columns]

In [14]:
summary = transacoes.groupby(by=['IdCliente'], as_index=False).agg({
    'IdTransacao' : ['count'],
    'QtdePontos' : ['sum', 'mean']
})
summary.head(10)

                              IdCliente IdTransacao QtdePontos
                                              count        sum        mean
0  000dc0f6-e4f2-4a42-b8cd-b586ed1c709a           2          2    1.000000
1  000ff655-fa9f-4baa-a108-47f581ec52a1         512      25086   48.996094
2  001749bd-37b5-4b1e-8111-f9fbba90f530           1         50   50.000000
3  0019bb9e-26d4-4ebf-8727-fc911ea28a92           2          2    1.000000
4  0028dda2-334f-40bb-9582-475fb6719471           4       1100  275.000000
5  0033b737-8235-4c0f-9801-dc4ca185af00         548       2561    4.673358
6  0068860b-c7eb-4312-830d-4ab9273c9b15           5        152   30.400000
7  0097ab76-4637-4ece-8ebc-ab6abd61d662           5        152   30.400000
8  00a2aa20-fd00-4c09-bab0-caf674e5cd30           6        104   17.333333
9  00a6d4c8-38e5-4e92-981e-4e4ac5084546         224       6637   29.629464

In [15]:
summary.columns

MultiIndex([(  'IdCliente',      ''),
            ('IdTransacao', 'count'),
            ( 'QtdePontos',   'sum'),
            ( 'QtdePontos',  'mean')],
           )

In [18]:
summary[('QtdePontos', 'mean')]
# summary['QtdePontos']['sum']

0          1.000000
1         48.996094
2         50.000000
3          1.000000
4        275.000000
           ...
3709      10.800000
3710       7.125000
3711      50.000000
3712       5.249351
3713    1000.000000
Name: (QtdePontos, mean), Length: 3714, dtype: float64

In [19]:
summary.columns = ['IdCliente', 'QtdeTransacao', 'totalPontos', 'avgPontos']
summary

,IdCliente,QtdeTransacao,totalPontos,avgPontos
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,2,2,1.000000
1,000ff655-fa9f-4baa-a108-47f581ec52a1,512,25086,48.996094
2,001749bd-37b5-4b1e-8111-f9fbba90f530,1,50,50.000000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,2,2,1.000000
4,0028dda2-334f-40bb-9582-475fb6719471,4,1100,275.000000
...,...,...,...,...
3709,ff1ceaef-650c-422b-bdc3-6984e29e7aa5,15,162,10.800000
3710,ff2cabd3-3316-4b3f-8494-c25f95e90524,8,57,7.125000
3711,ff4909ad-4e52-4767-a6fc-0fbd76e37857,1,50,50.000000
3712,ff5d2399-6b53-49f0-b41e-fdaaa0da172a,385,2021,5.249351
3713,fff7862d-4b2c-4140-a4c5-509b48ed31b4,1,1000,1000.000000

In [26]:
def amp_diff(x: pd.Series):
    amp = x.max() - x.min()
    media = x.mean()
    return np.sqrt((amp-media)**2)

def life_time(x: pd.Series):
    dt = pd.to_datetime(x)
    return (dt.max() - dt.min()).days

In [23]:
idades = pd.Series([42, 23, 21, 30, 35, 40, 27, 12, 34, 60])
amp_diff(idades)

np.float64(15.600000000000001)

In [29]:
df = transacoes.groupby(by=['IdCliente'], as_index=False).agg({
    'IdTransacao' : ['count'],
    'QtdePontos' : ['sum', 'mean', amp_diff],
    'DtCriacao' : [life_time]
})
df.head()

                              IdCliente IdTransacao QtdePontos              \
                                              count        sum        mean
0  000dc0f6-e4f2-4a42-b8cd-b586ed1c709a           2          2    1.000000
1  000ff655-fa9f-4baa-a108-47f581ec52a1         512      25086   48.996094
2  001749bd-37b5-4b1e-8111-f9fbba90f530           1         50   50.000000
3  0019bb9e-26d4-4ebf-8727-fc911ea28a92           2          2    1.000000
4  0028dda2-334f-40bb-9582-475fb6719471           4       1100  275.000000

               DtCriacao
      amp_diff life_time
0     1.000000        29
1  1451.003906       571
2    50.000000         0
3     1.000000        37
4  2625.000000         8

In [30]:
df.columns

MultiIndex([(  'IdCliente',          ''),
            ('IdTransacao',     'count'),
            ( 'QtdePontos',       'sum'),
            ( 'QtdePontos',      'mean'),
            ( 'QtdePontos',  'amp_diff'),
            (  'DtCriacao', 'life_time')],
           )