Exercício - Quem teve mais transações de Streak

In [1]:
import pandas as pd

In [4]:
transacoes = pd.read_csv('../data/transacoes.csv', sep=';')
transacoes.head()

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch

In [6]:
transacoes_produto = pd.read_csv('../data/transacao_produto.csv', sep=';')
transacoes_produto.head()

,idTransacaoProduto,IdTransacao,IdProduto,QtdeProduto,vlProduto
0,000026d0-4d4e-4fed-934a-9e5b26d9e379,d59d9859-8fb9-41cc-a296-be38c4dce8e4,5,1,1
1,00002f54-dd03-4b3f-ade0-22c3e61df8c2,519241fd-2676-49b2-8e74-0acc09a08f69,5,1,1
2,00004ee3-b894-4b8c-a36b-9480f0e643f3,03173ea0-9f4c-47fe-9982-5743027d1253,11,1,50
3,00006a7d-c83a-44ca-aad9-e8a2a2f1b64d,73993c42-d18f-4f51-82c4-25e13c29962c,11,1,50
4,0000991a-e6ae-4b9f-8747-c6cfe77890dd,db341350-16e4-49ea-96d4-c3e991e7c8c0,5,1,1

In [14]:
# 1;Airflow Lover;;lovers
# 10;Daily Loot;;rpg
# 11;Lista de presença;;present
# 12;Presença Streak;;present
# 13;R Lover;;lovers

produtos = pd.DataFrame({
    'IdProduto' : ['1', '10', '11', '12', '13'],
    'descProduto' : ['Airflow Lover', 'Daily Loot', 'Lista de presença', 'Presença Streak', 'R Lover'] 
})

produtos.head()

  IdProduto        descProduto
0         1      Airflow Lover
1        10         Daily Loot
2        11  Lista de presença
3        12    Presença Streak
4        13            R Lover

In [12]:
cliente_transacao_produto = transacoes.merge(
right=transacoes_produto, 
how='left', 
on=['IdTransacao'])[['IdTransacao', 'IdCliente', 'IdProduto']]

cliente_transacao_produto

,IdTransacao,IdCliente,IdProduto
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,5
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,5
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,5
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,5
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,5
...,...,...,...
337999,ffff52de-13fb-4405-a797-fddb5b4a48c5,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,5
338000,ffffb5ab-047e-43e4-bab3-ee2d19e9b7db,961622c3-3c29-4fa1-88d2-4f408d6d6ebb,5
338001,ffffc72e-d882-47f0-b933-cfd92c7e6621,2d3d2dce-d353-4961-ad39-46723efe2100,5
338002,ffffcd29-600c-4ae0-89b2-c62457eafc3f,c1a8d13d-cca9-4372-b195-9b0770d81a0d,5
338003,fffff928-9a18-4741-a516-3a92351d1d72,65662aff-44d6-4f06-b9d9-07445c6e5943,5

In [ ]:
df_full = cliente_transacao_produto.merge(
right=produtos, 
how='left', 
on=['IdProduto'])

df_full

,IdTransacao,IdCliente,IdProduto,descProduto
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,5,NaN
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,5,NaN
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,5,NaN
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,5,NaN
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,5,NaN
...,...,...,...,...
337999,ffff52de-13fb-4405-a797-fddb5b4a48c5,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,5,NaN
338000,ffffb5ab-047e-43e4-bab3-ee2d19e9b7db,961622c3-3c29-4fa1-88d2-4f408d6d6ebb,5,NaN
338001,ffffc72e-d882-47f0-b933-cfd92c7e6621,2d3d2dce-d353-4961-ad39-46723efe2100,5,NaN
338002,ffffcd29-600c-4ae0-89b2-c62457eafc3f,c1a8d13d-cca9-4372-b195-9b0770d81a0d,5,NaN
338003,fffff928-9a18-4741-a516-3a92351d1d72,65662aff-44d6-4f06-b9d9-07445c6e5943,5,NaN

In [27]:
filtro = df_full['descProduto'] == 'Presença Streak'
streak = df_full[filtro].groupby(by=['IdCliente'])[['IdTransacao']].count()

streak.sort_values(by=['IdTransacao'], ascending=False).head(3)

                                      IdTransacao
IdCliente
163022e8-12b8-486f-8604-57d8fa0ed7e1          451
6313ceac-7806-4d34-aedd-476eed7c853a          413
820c0e06-c405-4979-8975-ecfa17abb0f9          182

Tentando fazer de maneira mais enxuta e performática

In [36]:
produtos_filtro = produtos[produtos['descProduto'] == 'Presença Streak']

(transacoes.merge(right=transacoes_produto, how='left', on=['IdTransacao'])
            .merge(right=produtos_filtro, how='right', on=['IdProduto'])
            .groupby(by=['IdCliente'], as_index=False)[['IdTransacao']]
            .count()
            .sort_values(by=['IdTransacao'], ascending=False)
            .head(1)
)

                               IdCliente  IdTransacao
60  163022e8-12b8-486f-8604-57d8fa0ed7e1          451