Este notebook compreende os estudos práticos da biblioteca pandas para dados tabulares e manipulação de dados

Todo os estudos foram feitos com base no curso Pandas 2025 do canal do YouTube Téo Me Why.

Segue abaixo o link para a playlist e para a base de dados utilizada nos estudos:

    Curso: https://youtube.com/playlist?list=PLvlkVRRKOYFQHnDhjTmXLEz3HU5WTgOcF&si=iI3RDed5BIWAZmDZ
    Dataset: https://www.kaggle.com/datasets/teocalvo/teomewhy-loyalty-system

In [148]:
import pandas as pd
import numpy as np

In [149]:
idade = [31, 28, 40, 37, 35, 23, 43, 39, 22, 23, 30, 29, 41, 27, 32]

series_idades = pd.Series(idade)
series_idades

0     31
1     28
2     40
3     37
4     35
5     23
6     43
7     39
8     22
9     23
10    30
11    29
12    41
13    27
14    32
dtype: int64

In [150]:

media_idades = series_idades.mean()
summary_idades = series_idades.describe()

summary_idades

count    15.000000
mean     32.000000
std       6.897204
min      22.000000
25%      27.500000
50%      31.000000
75%      38.000000
max      43.000000
dtype: float64

In [151]:
# cada elemento dentro da Serie se associa a um índice, semelhante a uma chave de dicionário

print(series_idades[0]) # acessando elemento pelo seu índice

series_idades = series_idades.sort_values() # ordenando os valores da Serie
print(series_idades)

print(series_idades[0]) 
# ao tentar acessar novamente o elemento 0 após a ordenação, 
# o valor imprimido é o mesmo, já que a estrutura se comporta como chave:valor

print(series_idades.iloc[0]) # o iloc permite acessar o elemento a partir da posição dele dentro da Serie, que passa a se comportar como lista

31
8     22
5     23
9     23
13    27
1     28
11    29
10    30
0     31
14    32
4     35
3     37
7     39
2     40
12    41
6     43
dtype: int64
31
22

In [152]:
indexs = ['Mario', 'Remi', 'Ana', 'Jonatas', 'Olga', 'Helena', 'Ana', 'Bia', 
          'Beto', 'Pedro', 'Ronaldo', 'Vinicius', 'Fernando', 'Katia', 'Carlos']

# os índices das Series não precisam ser necessariamente númericos, nem únicos

series_idades = pd.Series(idade, index=indexs)
series_idades

series_idades['Ana'] # acessando o elemento no índice(chave) 'Ana', como possui mais de um, ele retornará todos que encontrar

Ana    40
Ana    43
dtype: int64

Dataframes

In [153]:
idade = [31, 28, 40, 37, 35, 23, 43, 39, 22, 23, 30, 29, 41, 27, 32]
nomes = ['Mario', 'Remi', 'Ana', 'Jonatas', 'Olga', 'Helena', 'Ana', 'Bia', 
          'Beto', 'Pedro', 'Ronaldo', 'Vinicius', 'Fernando', 'Katia', 'Carlos']

series_idades = pd.Series(idade)

df = pd.DataFrame() # cria um dataframe vazio

df['Idades'] = series_idades # adicionando uma Serie como uma nova coluna do dataframe e nomendo-a
df['Nomes'] = nomes # mesmo processo porém agora com uma lista
df

    Idades     Nomes
0       31     Mario
1       28      Remi
2       40       Ana
3       37   Jonatas
4       35      Olga
5       23    Helena
6       43       Ana
7       39       Bia
8       22      Beto
9       23     Pedro
10      30   Ronaldo
11      29  Vinicius
12      41  Fernando
13      27     Katia
14      32    Carlos

In [154]:
print(df['Nomes']) # Acessar uma coluna dentro do DataFrame a retorna como uma Serie

print(df.iloc[0]) # Acessa uma linha dentro do DataFrame e a retorna como uma Serie

# ao acessar um elemento dentro de um dataframe por coluna, o índice da Serie retornada será o mesmo do dataframe (0)
# ao acessar um elemento dentro de um dataframe por linha, o índice da Serie retornada será o nome das colunas (Idades, Nomes)

0        Mario
1         Remi
2          Ana
3      Jonatas
4         Olga
5       Helena
6          Ana
7          Bia
8         Beto
9        Pedro
10     Ronaldo
11    Vinicius
12    Fernando
13       Katia
14      Carlos
Name: Nomes, dtype: str
Idades       31
Nomes     Mario
Name: 0, dtype: object

In [155]:
# Ao acessar um elemento, seja por linha ou coluna, e obter uma Serie como resposta, é possível navegar dentro dela como uma Serie de fato

print(df.iloc[-1]['Nomes']) # Acessando a linha do último elemento do DataFrame e obtendo seu nome
print(df.iloc[-1]['Idades']) # Acessando a linha do último elemento do DataFrame e obtendo sua idade

Carlos
32

Importando dados

In [156]:
df = pd.read_csv('../data/clientes.csv')
df

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551
...,...,...,...,...,...,...,...,...,...
5612,ff5d2399-6b53-49f0-b41e-fdaaa0da172a,0,1,0,0,0,2021,2025-08-25 13:09:12.556,2026-01-30 14:43:50.139
5613,ff8d55dc-64fa-40de-992a-04a4155f5634,0,1,0,0,0,0,2025-07-12 13:50:37.959,2025-07-12 13:50:37.959
5614,ffcf3b9c-8cc8-4fca-a93a-e01a6fd830f0,1,1,1,0,0,0,2026-05-06 14:42:42.170,2026-05-06 14:44:23.800
5615,fff7862d-4b2c-4140-a4c5-509b48ed31b4,0,1,0,0,0,1000,2025-11-12 01:01:58.698,2025-11-12 01:02:16.561
5616,fff940d1-0786-4ee5-a75a-3bbda4e50f7a,0,1,0,0,0,0,2026-04-29 13:33:15.703,2026-04-29 13:33:15.703

In [157]:
df_2 = pd.read_csv('../data/transacao_produto.csv', sep=';')
df_2

#o dataset original está com separador ; e agora estou salvando o dataset em outro local com separador ,
df_2.to_csv('transacao_comma.csv', sep=',', index=False)

Amostras

In [158]:
df.head(n=10)

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551
5,002970bd-65c2-42bf-a17d-2bc5e95e2f0b,0,1,0,0,0,0,2025-07-16 09:36:45.831,2025-07-16 09:36:45.831
6,0033b737-8235-4c0f-9801-dc4ca185af00,0,1,0,0,0,2561,2025-02-19 12:48:24.632,2025-08-04 12:06:09.677
7,00417bdf-844f-40bf-92e1-d663373cbbd2,0,1,0,0,0,0,2025-11-10 03:14:09.875,2025-11-10 03:14:09.875
8,00511a44-026b-4ceb-80bf-c5f8937ef86c,0,1,0,0,0,0,2026-04-27 15:34:13.263,2026-04-27 15:34:13.263
9,005afca9-1872-44ad-9a88-93f9ac35ef9e,0,1,0,0,0,0,2026-05-06 19:58:08.644,2026-05-06 19:58:08.644

In [159]:
df.tail(n=10)

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
5607,fef56fd8-747a-4793-8fb4-13bc90aade9a,0,1,0,0,0,3,2025-10-01 12:39:41.018,2026-06-01 14:31:49.038
5608,ff07d926-f09e-420b-bebf-3dba02ae5dff,0,1,0,0,0,59,2025-01-21 11:49:58.172,2026-01-12 12:20:49.014
5609,ff1ceaef-650c-422b-bdc3-6984e29e7aa5,0,0,0,0,0,162,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
5610,ff2cabd3-3316-4b3f-8494-c25f95e90524,0,1,0,0,0,57,2025-02-10 11:12:30.631,2025-02-10 12:37:47.892
5611,ff4909ad-4e52-4767-a6fc-0fbd76e37857,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
5612,ff5d2399-6b53-49f0-b41e-fdaaa0da172a,0,1,0,0,0,2021,2025-08-25 13:09:12.556,2026-01-30 14:43:50.139
5613,ff8d55dc-64fa-40de-992a-04a4155f5634,0,1,0,0,0,0,2025-07-12 13:50:37.959,2025-07-12 13:50:37.959
5614,ffcf3b9c-8cc8-4fca-a93a-e01a6fd830f0,1,1,1,0,0,0,2026-05-06 14:42:42.170,2026-05-06 14:44:23.800
5615,fff7862d-4b2c-4140-a4c5-509b48ed31b4,0,1,0,0,0,1000,2025-11-12 01:01:58.698,2025-11-12 01:02:16.561
5616,fff940d1-0786-4ee5-a75a-3bbda4e50f7a,0,1,0,0,0,0,2026-04-29 13:33:15.703,2026-04-29 13:33:15.703

In [160]:
df.sample(10)

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
2663,77daec68-494b-4b2c-82b5-eb85743cc364,0,0,0,0,0,153,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
2851,80b441a7-f31e-4302-b2dc-637adb8baffb,0,1,0,0,0,153,2025-03-26 11:35:21.234,2025-04-02 11:36:54.741
3046,88b67027-bc1e-4152-a8e6-ae3f9655c673,1,0,0,0,0,2902,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
5256,ee785d9e-1b1c-46b7-aa07-a04e7e36fd14,1,1,1,0,0,0,2026-01-20 14:18:13.576,2026-01-20 14:18:45.147
3900,aeaf1f62-95db-42fd-959d-30c8dfd3327d,0,0,0,0,0,151,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
1587,4621e46a-2698-4d4d-a5c0-8b40d71bed92,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3176,8e441868-82c3-4444-ac86-8e994250b26b,0,1,0,0,0,0,2025-10-26 20:56:42.108,2025-10-26 20:56:42.108
3217,9076694c-1179-47cd-acda-ca278b0fb172,0,1,0,0,0,0,2026-01-05 22:43:42.469,2026-01-05 22:43:42.469
923,286d6693-12c0-4066-a9ee-8963ff551110,0,0,0,0,0,53,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4387,c6ba4404-a0a9-49ba-8519-c2773580678c,0,1,0,0,0,0,2026-01-08 07:21:05.873,2026-01-08 07:21:05.873

Atributos de um dataframe

In [161]:
print(f'O dataframe possui {df.shape[0]} linhas e {df.shape[1]} colunas')

O dataframe possui 5617 linhas e 9 colunas

In [162]:
df.columns

Index(['idCliente', 'flEmail', 'flTwitch', 'flYouTube', 'flBlueSky',
       'flInstagram', 'qtdePontos', 'DtCriacao', 'DtAtualizacao'],
      dtype='str')

In [163]:
df.index

RangeIndex(start=0, stop=5617, step=1)

In [164]:
df.dtypes

idCliente          str
flEmail          int64
flTwitch         int64
flYouTube        int64
flBlueSky        int64
flInstagram      int64
qtdePontos       int64
DtCriacao          str
DtAtualizacao      str
dtype: object

In [165]:
df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 5617 entries, 0 to 5616
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   idCliente      5617 non-null   str
 1   flEmail        5617 non-null   int64
 2   flTwitch       5617 non-null   int64
 3   flYouTube      5617 non-null   int64
 4   flBlueSky      5617 non-null   int64
 5   flInstagram    5617 non-null   int64
 6   qtdePontos     5617 non-null   int64
 7   DtCriacao      5617 non-null   str
 8   DtAtualizacao  5617 non-null   str
dtypes: int64(6), str(3)
memory usage: 1.5 MB

In [166]:
df_trans = pd.read_csv('../data/transacoes.csv', sep= ';')
df_trans

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch
...,...,...,...,...,...
337069,ffff52de-13fb-4405-a797-fddb5b4a48c5,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-24 12:22:26.313,1,twitch
337070,ffffb5ab-047e-43e4-bab3-ee2d19e9b7db,961622c3-3c29-4fa1-88d2-4f408d6d6ebb,2024-08-16 13:09:42.576,1,twitch
337071,ffffc72e-d882-47f0-b933-cfd92c7e6621,2d3d2dce-d353-4961-ad39-46723efe2100,2024-02-06 11:51:24.788,1,twitch
337072,ffffcd29-600c-4ae0-89b2-c62457eafc3f,c1a8d13d-cca9-4372-b195-9b0770d81a0d,2026-04-14 12:03:03.720,1,twitch
337073,fffff928-9a18-4741-a516-3a92351d1d72,65662aff-44d6-4f06-b9d9-07445c6e5943,2024-08-21 14:13:31.788,1,twitch

In [167]:
print(f'dataframe possui {df_trans.shape[0]} linhas e {df_trans.shape[1]} colunas')

dataframe possui 337074 linhas e 5 colunas

In [168]:
df_trans.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 337074 entries, 0 to 337073
Data columns (total 5 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   IdTransacao        337074 non-null  str
 1   IdCliente          337074 non-null  str
 2   DtCriacao          337074 non-null  str
 3   QtdePontos         337074 non-null  int64
 4   DescSistemaOrigem  337074 non-null  str
dtypes: int64(1), str(4)
memory usage: 98.0 MB

In [169]:
renamed_columns = {
    'DtCriacao' : 'Data_Criacao',
    'QtdePontos' : 'Pts',
    'DescSistemaOrigem' : 'Origem'
}

df_trans.rename(columns=renamed_columns, inplace=True)

df_trans

,IdTransacao,IdCliente,Data_Criacao,Pts,Origem
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch
...,...,...,...,...,...
337069,ffff52de-13fb-4405-a797-fddb5b4a48c5,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-24 12:22:26.313,1,twitch
337070,ffffb5ab-047e-43e4-bab3-ee2d19e9b7db,961622c3-3c29-4fa1-88d2-4f408d6d6ebb,2024-08-16 13:09:42.576,1,twitch
337071,ffffc72e-d882-47f0-b933-cfd92c7e6621,2d3d2dce-d353-4961-ad39-46723efe2100,2024-02-06 11:51:24.788,1,twitch
337072,ffffcd29-600c-4ae0-89b2-c62457eafc3f,c1a8d13d-cca9-4372-b195-9b0770d81a0d,2026-04-14 12:03:03.720,1,twitch
337073,fffff928-9a18-4741-a516-3a92351d1d72,65662aff-44d6-4f06-b9d9-07445c6e5943,2024-08-21 14:13:31.788,1,twitch

In [170]:
df_trans[['IdCliente', 'Data_Criacao']].head(10)

                              IdCliente             Data_Criacao
0  24782f0b-4683-4f35-976a-ea21d6714ba6  2025-09-17 12:28:41.864
1  252a0923-3f79-45bb-b664-3040235c6c58  2024-07-23 12:49:49.874
2  30f45a6d-ada5-4a17-8338-710e414eb6c6  2025-09-17 13:38:57.479
3  65662aff-44d6-4f06-b9d9-07445c6e5943  2025-10-03 12:23:39.779
4  5f8fcbe0-6014-43f8-8b83-38cf2f4887b3  2024-02-20 13:21:45.613
5  3884c92f-a635-4b67-9e5a-97730829cdca  2024-02-05 13:27:18.987
6  3b878853-34a5-44be-9a8e-05642b853dc6  2025-09-30 12:02:16.448
7  e2624c1c-c8af-4622-94e0-f3470037292f  2024-06-20 19:22:45.600
8  7df60476-b880-485a-9430-ededf50a9bbb  2026-02-25 12:52:50.780
9  9aba2685-7c0a-4d1f-8e22-0c47ca0af580  2024-03-18 13:04:21.814

In [171]:
df_trans['Pts']
#print(type(df_trans['Pts'])) # Retorna uma Série

0         1
1         1
2         1
3         1
4         1
         ..
337069    1
337070    1
337071    1
337072    1
337073    1
Name: Pts, Length: 337074, dtype: int64

In [172]:
df_trans[['Pts']]
#print(type(df_trans[['Pts']])) # Retorna um dataframe com uma única coluna

        Pts
0         1
1         1
2         1
3         1
4         1
...     ...
337069    1
337070    1
337071    1
337072    1
337073    1

[337074 rows x 1 columns]

In [173]:
colunas = list(df_trans.columns)
colunas.sort()
colunas

df_trans[colunas]

,Data_Criacao,IdCliente,IdTransacao,Origem,Pts
0,2025-09-17 12:28:41.864,24782f0b-4683-4f35-976a-ea21d6714ba6,0000520a-a4e5-4977-b360-17be62fa0f2b,twitch,1
1,2024-07-23 12:49:49.874,252a0923-3f79-45bb-b664-3040235c6c58,000060e8-aa76-4286-a8d7-f30e6fa47edd,twitch,1
2,2025-09-17 13:38:57.479,30f45a6d-ada5-4a17-8338-710e414eb6c6,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,twitch,1
3,2025-10-03 12:23:39.779,65662aff-44d6-4f06-b9d9-07445c6e5943,0000c010-a592-46f7-8b0b-6f841bee64ba,twitch,1
4,2024-02-20 13:21:45.613,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,0000dfbb-e14e-4ea7-a57f-60236869fffe,twitch,1
...,...,...,...,...,...
337069,2024-02-24 12:22:26.313,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,ffff52de-13fb-4405-a797-fddb5b4a48c5,twitch,1
337070,2024-08-16 13:09:42.576,961622c3-3c29-4fa1-88d2-4f408d6d6ebb,ffffb5ab-047e-43e4-bab3-ee2d19e9b7db,twitch,1
337071,2024-02-06 11:51:24.788,2d3d2dce-d353-4961-ad39-46723efe2100,ffffc72e-d882-47f0-b933-cfd92c7e6621,twitch,1
337072,2026-04-14 12:03:03.720,c1a8d13d-cca9-4372-b195-9b0770d81a0d,ffffcd29-600c-4ae0-89b2-c62457eafc3f,twitch,1
337073,2024-08-21 14:13:31.788,65662aff-44d6-4f06-b9d9-07445c6e5943,fffff928-9a18-4741-a516-3a92351d1d72,twitch,1

In [174]:
df = pd.read_csv('../data/transacoes.csv', sep=';')
df.head()

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch

In [175]:
pontos = [10, 1, 1, 1, 30, 100, 25, 130, 50, 40, 1, 1, 1, 1, 100, 10, 10, 25]

maiores_pontos = [i for i in pontos if i >= 50]
maiores_pontos

filtro = []
for i in pontos:
    filtro.append(i>=50)

resultado = []
for i in range(len(pontos)):
    if filtro[i]:
        resultado.append(pontos[i])

resultado

[100, 130, 50, 100]

In [176]:
cadastro = pd.DataFrame({
    'nome' : ['Gabriel', 'Ana', 'Mario'],
    'idade' : [15, 22, 18],
    'uf' : ['es', 'pb', 'ms']
})

filtro = cadastro['idade'] >= 18
filtro

cadastro[filtro]

    nome  idade  uf
1    Ana     22  pb
2  Mario     18  ms

In [177]:
cadastro[cadastro['idade'] >= 18]

    nome  idade  uf
1    Ana     22  pb
2  Mario     18  ms

In [178]:
filtro_pontos = (df['QtdePontos'] >= 50) & (df['DescSistemaOrigem'] != 'twitch')
df[filtro_pontos]

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
491,005cfd74-deb6-4176-9570-ea3fc30c6954,054366e2-a4bb-44ec-8abe-dbcecc3fbdbe,2026-05-23 14:11:50.826,1000,cursos
1578,012c926c-d329-4f92-ada6-82481285b944,890762ae-991c-40df-ab45-76486b14289d,2025-07-15 13:37:59.899,1000,cursos
2876,02223aa2-5d27-4ecc-911b-a67354db77df,6bcb9305-ac81-472a-9fd3-5522f465e8f1,2025-07-30 18:22:15.891,1000,cursos
2903,0226feae-f411-4d8a-aa86-7d897a459653,df0cc1e9-f2d0-421b-b018-eadb75bceeaa,2026-02-25 16:00:17.644,1000,cursos
3409,0286436a-2a32-4dd3-b4ce-3f851a0b92d5,274dba93-004d-4cda-9d77-dd61282f201a,2026-01-07 19:28:39.338,1000,cursos
...,...,...,...,...,...
335100,fe7f2fda-bbf0-4df9-a38d-2d7d53dd7f33,fdfd6f2f-9c11-466a-bde8-c84cbf15151e,2025-08-16 06:05:08.317,1000,cursos
335430,febb77b3-3aca-44c1-b24d-210def427ea2,560e5a7f-15dc-483f-b8ad-58d6d4e6a1db,2026-02-18 01:40:40.089,1000,cursos
335899,ff1c50d5-12b4-4910-9133-9686a653a4bc,5ff083a7-e818-4367-bda5-a9cee8dec654,2026-07-13 12:23:01.157,50,cursos
336730,ffba557e-3e3f-49b3-9856-9394a8113acf,735e2557-82cc-44e0-b534-a4de988c66b0,2026-05-27 18:19:38.491,1000,cursos
337016,fff3310d-0af7-429b-936a-b1307ccec508,5802f8c5-83b5-4c0e-ba30-1f2ec23ff284,2026-02-10 16:57:22.668,1000,cursos

In [179]:
df_tp = pd.read_csv('../data/transacao_produto.csv', sep = ';')
df_tp

filtro_ids = (df_tp['IdProduto'] == '5') | (df_tp['IdProduto'] == '11')

df_tp[filtro_ids]

,idTransacaoProduto,IdTransacao,IdProduto,QtdeProduto,vlProduto
0,000026d0-4d4e-4fed-934a-9e5b26d9e379,d59d9859-8fb9-41cc-a296-be38c4dce8e4,5,1,1
1,00002f54-dd03-4b3f-ade0-22c3e61df8c2,519241fd-2676-49b2-8e74-0acc09a08f69,5,1,1
2,00004ee3-b894-4b8c-a36b-9480f0e643f3,03173ea0-9f4c-47fe-9982-5743027d1253,11,1,50
3,00006a7d-c83a-44ca-aad9-e8a2a2f1b64d,73993c42-d18f-4f51-82c4-25e13c29962c,11,1,50
4,0000991a-e6ae-4b9f-8747-c6cfe77890dd,db341350-16e4-49ea-96d4-c3e991e7c8c0,5,1,1
...,...,...,...,...,...
337999,fffd9569-31e6-4515-8494-4edeabc0cfc2,6baf63b1-d05a-419d-a84f-abdf6906fef8,11,1,50
338000,fffe7e68-c450-4025-9469-e5cbe7699b49,90f7149b-5794-4d49-9239-c3bddb5b0980,5,1,1
338001,fffead0f-105b-4517-ac6f-b60ffd66f0dd,a5240b8c-c015-4d4c-8e34-2e81973ad084,5,1,1
338002,ffff210a-2594-42fa-8d85-c97483817542,4d7c74c0-5ca0-4786-823b-b393d505c2e6,5,1,1
338003,ffff2827-d194-42ac-8a62-90b1a745eddf,410a177d-1234-4a0f-b1e2-456db06a99ba,5,1,1

In [180]:
clientes = pd.read_csv('../data/clientes.csv')
filtro = clientes['qtdePontos'] == 0
clientes_0 = clientes[filtro].copy()
clientes_0['flag'] = 1

clientes_0

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao,flag
5,002970bd-65c2-42bf-a17d-2bc5e95e2f0b,0,1,0,0,0,0,2025-07-16 09:36:45.831,2025-07-16 09:36:45.831,1
7,00417bdf-844f-40bf-92e1-d663373cbbd2,0,1,0,0,0,0,2025-11-10 03:14:09.875,2025-11-10 03:14:09.875,1
8,00511a44-026b-4ceb-80bf-c5f8937ef86c,0,1,0,0,0,0,2026-04-27 15:34:13.263,2026-04-27 15:34:13.263,1
9,005afca9-1872-44ad-9a88-93f9ac35ef9e,0,1,0,0,0,0,2026-05-06 19:58:08.644,2026-05-06 19:58:08.644,1
10,00684343-40b5-4ce7-b2e8-71a5340973bf,0,0,0,0,0,0,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000,1
...,...,...,...,...,...,...,...,...,...,...
5600,feaf434b-e428-4445-a86e-6218c40d55ae,0,1,0,0,0,0,2025-07-08 05:14:32.687,2025-07-08 05:14:32.687,1
5606,fef10bef-475a-4189-91ff-a3333ee5d593,1,1,1,0,0,0,2026-06-02 01:09:46.668,2026-06-02 01:10:23.322,1
5613,ff8d55dc-64fa-40de-992a-04a4155f5634,0,1,0,0,0,0,2025-07-12 13:50:37.959,2025-07-12 13:50:37.959,1
5614,ffcf3b9c-8cc8-4fca-a93a-e01a6fd830f0,1,1,1,0,0,0,2026-05-06 14:42:42.170,2026-05-06 14:44:23.800,1
5616,fff940d1-0786-4ee5-a75a-3bbda4e50f7a,0,1,0,0,0,0,2026-04-29 13:33:15.703,2026-04-29 13:33:15.703,1

In [181]:
# Como os dfs estão começando a ficar confusos, irei normalizar eles com nomes padrões que utilizarei daqui para baixo
clientes = pd.read_csv('../data/clientes.csv')
transacao = df_trans.copy() # refere ao transacao.csv
trans_prod = df_tp.copy() # refere ao transacao_produto.csv

In [182]:
# somando 100 pontos para cada cliente

clientes['qtdePontos'] + 100

0         102
1       25186
2         150
3         102
4        1200
        ...
5612     2121
5613      100
5614      100
5615     1100
5616      100
Name: qtdePontos, Length: 5617, dtype: int64

In [183]:
# criando uma nova coluna de verificação de email ou twitch (de forma numérica)

clientes['Email_ou_Twitch'] = clientes['flEmail'] + clientes['flTwitch']
clientes.head(10)

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao,Email_ou_Twitch
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364,1
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697,0
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000,0
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000,0
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551,2
5,002970bd-65c2-42bf-a17d-2bc5e95e2f0b,0,1,0,0,0,0,2025-07-16 09:36:45.831,2025-07-16 09:36:45.831,1
6,0033b737-8235-4c0f-9801-dc4ca185af00,0,1,0,0,0,2561,2025-02-19 12:48:24.632,2025-08-04 12:06:09.677,1
7,00417bdf-844f-40bf-92e1-d663373cbbd2,0,1,0,0,0,0,2025-11-10 03:14:09.875,2025-11-10 03:14:09.875,1
8,00511a44-026b-4ceb-80bf-c5f8937ef86c,0,1,0,0,0,0,2026-04-27 15:34:13.263,2026-04-27 15:34:13.263,1
9,005afca9-1872-44ad-9a88-93f9ac35ef9e,0,1,0,0,0,0,2026-05-06 19:58:08.644,2026-05-06 19:58:08.644,1

In [184]:
# explorando quantas redes sociais cada cliente possui cadastradas

clientes['Redes_Sociais'] = clientes['flEmail'] + clientes['flTwitch'] + clientes['flYouTube'] + clientes['flBlueSky'] + clientes['flInstagram']
clientes.head(10)
# clientes['flEmail'] + clientes['flTwitch'] + clientes['flYouTube'] + clientes['flBlueSky'] + clientes['flInstagram']

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao,Email_ou_Twitch,Redes_Sociais
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364,1,1
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697,0,0
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000,0,0
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000,0,0
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551,2,3
5,002970bd-65c2-42bf-a17d-2bc5e95e2f0b,0,1,0,0,0,0,2025-07-16 09:36:45.831,2025-07-16 09:36:45.831,1,1
6,0033b737-8235-4c0f-9801-dc4ca185af00,0,1,0,0,0,2561,2025-02-19 12:48:24.632,2025-08-04 12:06:09.677,1,1
7,00417bdf-844f-40bf-92e1-d663373cbbd2,0,1,0,0,0,0,2025-11-10 03:14:09.875,2025-11-10 03:14:09.875,1,1
8,00511a44-026b-4ceb-80bf-c5f8937ef86c,0,1,0,0,0,0,2026-04-27 15:34:13.263,2026-04-27 15:34:13.263,1,1
9,005afca9-1872-44ad-9a88-93f9ac35ef9e,0,1,0,0,0,0,2026-05-06 19:58:08.644,2026-05-06 19:58:08.644,1,1

In [185]:
# Criando uma flag de quem possui todas as redes sociais

clientes['Todas_Social'] = clientes['flEmail'] * clientes['flTwitch'] * clientes['flYouTube'] * clientes['flBlueSky'] * clientes['flInstagram']
clientes

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao,Email_ou_Twitch,Redes_Sociais,Todas_Social
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364,1,1,0
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697,0,0,0
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000,0,0,0
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000,0,0,0
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551,2,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...
5612,ff5d2399-6b53-49f0-b41e-fdaaa0da172a,0,1,0,0,0,2021,2025-08-25 13:09:12.556,2026-01-30 14:43:50.139,1,1,0
5613,ff8d55dc-64fa-40de-992a-04a4155f5634,0,1,0,0,0,0,2025-07-12 13:50:37.959,2025-07-12 13:50:37.959,1,1,0
5614,ffcf3b9c-8cc8-4fca-a93a-e01a6fd830f0,1,1,1,0,0,0,2026-05-06 14:42:42.170,2026-05-06 14:44:23.800,2,3,0
5615,fff7862d-4b2c-4140-a4c5-509b48ed31b4,0,1,0,0,0,1000,2025-11-12 01:01:58.698,2025-11-12 01:02:16.561,1,1,0
5616,fff940d1-0786-4ee5-a75a-3bbda4e50f7a,0,1,0,0,0,0,2026-04-29 13:33:15.703,2026-04-29 13:33:15.703,1,1,0

In [186]:
# Verificando quantas pessoas possuem todas a redes sociais cadastradas

filtro = clientes['Todas_Social'] > 0
clientes[filtro]

Empty DataFrame
Columns: [idCliente, flEmail, flTwitch, flYouTube, flBlueSky, flInstagram, qtdePontos, DtCriacao, DtAtualizacao, Email_ou_Twitch, Redes_Sociais, Todas_Social]
Index: []

ninguém possui todas as redes sociais cadastradas
    - Falta de engajamento ?
    - Disparidade de cadastro entre redes sociais (mais usadas e menos usadas) ?

In [187]:
filtro = clientes['flBlueSky'] > 0
clientes[filtro]

Empty DataFrame
Columns: [idCliente, flEmail, flTwitch, flYouTube, flBlueSky, flInstagram, qtdePontos, DtCriacao, DtAtualizacao, Email_ou_Twitch, Redes_Sociais, Todas_Social]
Index: []

Ninguém possui a conta da rede social Blue Sky cadastrada.

In [188]:
clientes['qtdePontos'].describe()

count     5617.000000
mean       440.201531
std       1332.417690
min        -10.000000
25%          0.000000
50%         51.000000
75%        283.000000
max      32860.000000
Name: qtdePontos, dtype: float64

In [189]:
clientes['logPontos'] = np.log( clientes['qtdePontos']+1 )
clientes['logPontos'].describe()

c:\Users\ACER\AppData\Local\Programs\Python\Python314\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

count    5616.000000
mean        3.451927
std         2.815050
min         0.000000
25%         0.000000
50%         3.951244
75%         5.650729
max        10.400042
Name: logPontos, dtype: float64

In [190]:
# Pegando o cliente com maior valor de pontos

max_ponto = clientes['qtdePontos'].max()
filtro = clientes['qtdePontos'] == max_ponto
clientes[filtro]

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao,Email_ou_Twitch,Redes_Sociais,Todas_Social,logPontos
972,2a9d4ba3-4c58-47f9-8dc4-6f9cb50be1b1,1,1,0,0,0,32860,2025-03-07 12:59:11.756,2026-07-14 12:37:09.970,2,2,0,10.400042

In [191]:
# Pegando os 10 clientes com maior quantidade de pontos

# clientes['qtdePontos'].sort_values(ascending=False).head(10)

clientes.sort_values(by='qtdePontos', ascending=False).head(10)

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao,Email_ou_Twitch,Redes_Sociais,Todas_Social,logPontos
972,2a9d4ba3-4c58-47f9-8dc4-6f9cb50be1b1,1,1,0,0,0,32860,2025-03-07 12:59:11.756,2026-07-14 12:37:09.970,2,2,0,10.400042
4793,d7f7eb75-4f0b-4d15-960d-8efe5ca7dd7e,0,0,0,0,0,25979,2025-03-07 12:36:50.254,2026-06-02 12:32:23.118,0,0,0,10.165082
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697,0,0,0,10.130105
2145,5ff083a7-e818-4367-bda5-a9cee8dec654,0,1,0,0,0,19883,2025-02-11 11:03:09.016,2026-07-14 13:16:26.213,1,1,0,9.897671
4944,def56b88-a05b-465b-80ee-702831d3f535,0,1,0,0,0,18077,2025-02-12 11:38:11.917,2026-07-14 12:09:53.263,1,1,0,9.802451
1314,391e5f20-0a0a-4b5a-ae6b-0b3b2a7cdd13,0,1,0,0,0,16260,2025-03-07 12:01:41.048,2026-07-14 13:20:33.851,1,1,0,9.696525
2839,803debdb-8136-4cb5-af29-dcd8db36bf2c,0,1,0,0,0,16246,2025-02-28 13:19:26.475,2025-07-02 13:44:45.438,1,1,0,9.695664
4354,c52fb72f-b3dc-4650-9182-b08b5ed1420a,1,1,0,0,0,13976,2024-02-01 00:00:00.000,2026-07-14 12:49:19.309,2,2,0,9.545168
268,0ade65a7-c1b0-4aa5-8ab6-a4ad78028037,0,1,0,0,0,13436,2025-03-07 13:04:22.172,2026-04-22 12:23:20.883,1,1,0,9.505767
1489,41f925fd-9aa0-4043-9774-212c538133cc,1,1,0,0,0,12670,2025-03-06 11:48:20.416,2025-03-06 11:48:20.416,2,2,0,9.447071

In [192]:
df_salario = pd.DataFrame(
    {
        'nome' : ['Gabriel', 'Theo', 'Ana', 'Carlos'],
        'idade' : [27, 31, 22, 30],
        'salario': [2300, 4500, 3200, 2300]
    }
)

df_salario

      nome  idade  salario
0  Gabriel     27     2300
1     Theo     31     4500
2      Ana     22     3200
3   Carlos     30     2300

In [193]:
df_salario.sort_values(by=['salario', 'idade'], ascending=[False, True])

      nome  idade  salario
1     Theo     31     4500
2      Ana     22     3200
0  Gabriel     27     2300
3   Carlos     30     2300

In [194]:
clientes['qtdePontos'].astype(float)

0           2.0
1       25086.0
2          50.0
3           2.0
4        1100.0
         ...
5612     2021.0
5613        0.0
5614        0.0
5615     1000.0
5616        0.0
Name: qtdePontos, Length: 5617, dtype: float64

In [195]:
clientes['DtCriacao'] = clientes['DtCriacao'].replace({
    '2024-02-01 00:00:00.000' : '0000-00-00 00:00:00.000'
})

# pd.to_datetime(clientes['DtCriacao'])

clientes['DtCriacao'] = clientes['DtCriacao'].replace({
    '0000-00-00 00:00:00.000' : '2024-02-01 09:00:00.000'
})

clientes['DtCriacao'] = pd.to_datetime(clientes['DtCriacao'])
clientes['DtCriacao']

0      2025-11-13 12:03:56.114
1      2024-02-01 09:00:00.000
2      2024-02-01 09:00:00.000
3      2024-02-01 09:00:00.000
4      2025-10-29 02:08:18.367
                 ...
5612   2025-08-25 13:09:12.556
5613   2025-07-12 13:50:37.959
5614   2026-05-06 14:42:42.170
5615   2025-11-12 01:01:58.698
5616   2026-04-29 13:33:15.703
Name: DtCriacao, Length: 5617, dtype: datetime64[us]

In [196]:
clientes['DtCriacao'].dt.month_name()

0       November
1       February
2       February
3       February
4        October
          ...
5612      August
5613        July
5614         May
5615    November
5616       April
Name: DtCriacao, Length: 5617, dtype: str

In [197]:
testes_nas = pd.DataFrame({
    'nome': ['Gabriel', None, None, 'Márcia', 'Luanna'],
    'idade' : [22, 19, None, 41, None],
    'salario' : [1200, 3450, None, None, 4000]
})

testes_nas

      nome  idade  salario
0  Gabriel   22.0   1200.0
1      NaN   19.0   3450.0
2      NaN    NaN      NaN
3   Márcia   41.0      NaN
4   Luanna    NaN   4000.0

In [198]:
testes_nas.dropna(how='any')

      nome  idade  salario
0  Gabriel   22.0   1200.0

In [199]:
testes_nas.dropna(how='all')

      nome  idade  salario
0  Gabriel   22.0   1200.0
1      NaN   19.0   3450.0
3   Márcia   41.0      NaN
4   Luanna    NaN   4000.0

In [200]:
testes_nas.dropna(how='any', subset=['idade', 'salario'])

      nome  idade  salario
0  Gabriel   22.0   1200.0
1      NaN   19.0   3450.0

In [201]:
medias = testes_nas[['idade', 'salario']].mean()

testes_nas.fillna(medias)

      nome      idade      salario
0  Gabriel  22.000000  1200.000000
1      NaN  19.000000  3450.000000
2      NaN  27.333333  2883.333333
3   Márcia  41.000000  2883.333333
4   Luanna  27.333333  4000.000000

In [202]:
testes_dup = pd.DataFrame({
    'nome' : ['gabriel', 'lara', 'maria', 'teo', 'davi', 'gabriel', 'davi', 'maria'],
    'sobrenome' : ['carvalho', 'carvalho', 'tenorio', 'tenorio', 'pereira', 'carvalho', 'tenorio', 'pereira'],
    'salario' : [1400, 2300, 2300, 5500, 6000, 1230, 2000, 800]
})

testes_dup

      nome sobrenome  salario
0  gabriel  carvalho     1400
1     lara  carvalho     2300
2    maria   tenorio     2300
3      teo   tenorio     5500
4     davi   pereira     6000
5  gabriel  carvalho     1230
6     davi   tenorio     2000
7    maria   pereira      800

In [203]:
testes_dup.drop_duplicates(keep='last', subset=['nome', 'sobrenome'])

      nome sobrenome  salario
1     lara  carvalho     2300
2    maria   tenorio     2300
3      teo   tenorio     5500
4     davi   pereira     6000
5  gabriel  carvalho     1230
6     davi   tenorio     2000
7    maria   pereira      800

In [204]:
testes_dup.sort_values(by='salario', ascending=False).drop_duplicates(keep='first', subset=['nome', 'sobrenome'])

      nome sobrenome  salario
4     davi   pereira     6000
3      teo   tenorio     5500
2    maria   tenorio     2300
1     lara  carvalho     2300
6     davi   tenorio     2000
0  gabriel  carvalho     1400
7    maria   pereira      800

In [205]:
primeira_transacao = transacao.copy()
primeira_transacao.head()

,IdTransacao,IdCliente,Data_Criacao,Pts,Origem
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch

In [206]:
primeira_transacao = primeira_transacao.sort_values(by='Data_Criacao')
primeira_transacao

,IdTransacao,IdCliente,Data_Criacao,Pts,Origem
330916,fb4e3102-6125-414e-b086-e7f641e38f93,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 11:53:23.774,1,twitch
4605,036b8d66-8adf-479b-ba0f-cb0e3207acb0,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 11:53:24.643,1,twitch
21302,10166182-a164-4608-8cdf-35e4450b2bd7,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 12:11:44.728,500,twitch
4828,03974c58-e86e-4b6b-8143-8f89ca870d09,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 12:19:41.063,1,twitch
305766,e84703a6-b606-4096-a2f3-514971c16c5c,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 12:31:46.288,500,twitch
...,...,...,...,...,...
143127,6cec7070-494e-4321-8137-e6661fb7b9e5,6313ceac-7806-4d34-aedd-476eed7c853a,2026-07-14 15:49:51.906,50,twitch
193551,93348d46-1c8c-47fd-ae35-2db6eccc1bca,6313ceac-7806-4d34-aedd-476eed7c853a,2026-07-14 15:49:56.091,50,twitch
213273,a20cc0a2-28eb-498f-ac5f-de28bfab5ef7,360c6300-c722-4de2-bc7c-1bcb4db2adaa,2026-07-14 18:10:44.412,1000,cursos
181504,8a1d923d-5879-44eb-8079-61cfd714dbbc,360c6300-c722-4de2-bc7c-1bcb4db2adaa,2026-07-14 18:10:58.863,1000,cursos
312832,ed9b2680-31c0-4a6d-a7cd-d33fd0663ff8,163022e8-12b8-486f-8604-57d8fa0ed7e1,2026-07-14 22:13:47.163,50,twitch

In [207]:
primeira_transacao['data'] = pd.to_datetime(primeira_transacao['Data_Criacao']).dt.date
primeira_transacao

,IdTransacao,IdCliente,Data_Criacao,Pts,Origem,data
330916,fb4e3102-6125-414e-b086-e7f641e38f93,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 11:53:23.774,1,twitch,2024-01-27
4605,036b8d66-8adf-479b-ba0f-cb0e3207acb0,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 11:53:24.643,1,twitch,2024-01-27
21302,10166182-a164-4608-8cdf-35e4450b2bd7,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 12:11:44.728,500,twitch,2024-01-27
4828,03974c58-e86e-4b6b-8143-8f89ca870d09,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 12:19:41.063,1,twitch,2024-01-27
305766,e84703a6-b606-4096-a2f3-514971c16c5c,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 12:31:46.288,500,twitch,2024-01-27
...,...,...,...,...,...,...
143127,6cec7070-494e-4321-8137-e6661fb7b9e5,6313ceac-7806-4d34-aedd-476eed7c853a,2026-07-14 15:49:51.906,50,twitch,2026-07-14
193551,93348d46-1c8c-47fd-ae35-2db6eccc1bca,6313ceac-7806-4d34-aedd-476eed7c853a,2026-07-14 15:49:56.091,50,twitch,2026-07-14
213273,a20cc0a2-28eb-498f-ac5f-de28bfab5ef7,360c6300-c722-4de2-bc7c-1bcb4db2adaa,2026-07-14 18:10:44.412,1000,cursos,2026-07-14
181504,8a1d923d-5879-44eb-8079-61cfd714dbbc,360c6300-c722-4de2-bc7c-1bcb4db2adaa,2026-07-14 18:10:58.863,1000,cursos,2026-07-14
312832,ed9b2680-31c0-4a6d-a7cd-d33fd0663ff8,163022e8-12b8-486f-8604-57d8fa0ed7e1,2026-07-14 22:13:47.163,50,twitch,2026-07-14

In [208]:
primeira_transacao.drop_duplicates(keep='first', subset=['IdCliente', 'data'])

,IdTransacao,IdCliente,Data_Criacao,Pts,Origem,data
330916,fb4e3102-6125-414e-b086-e7f641e38f93,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 11:53:23.774,1,twitch,2024-01-27
226647,ac18e5fd-eb6e-4d83-9bf1-bd8973fcd1b4,2d3d2dce-d353-4961-ad39-46723efe2100,2024-01-29 11:55:05.127,1,twitch,2024-01-29
51598,270948e3-a015-4255-be6a-36010d26b74d,c4f241f8-2140-4f72-b1a3-904fcc51e38c,2024-01-29 11:57:14.602,1,twitch,2024-01-29
8053,060cc463-a074-4c65-867c-bb88606a6123,65662aff-44d6-4f06-b9d9-07445c6e5943,2024-01-29 11:59:41.832,1,twitch,2024-01-29
105723,505b94d7-9bcb-48f1-803d-337245f02c45,03d75a45-0b36-4fd7-a84e-7b36912f1998,2024-01-29 12:00:02.504,1,twitch,2024-01-29
...,...,...,...,...,...,...
31279,17a8f80e-a135-4042-9d48-e97a3ac29aa6,dc4e44bf-80c7-4888-bef2-4234b4ecfb6e,2026-07-14 14:02:55.187,1,twitch,2026-07-14
258655,c47b0cc5-4078-439b-b5eb-213d80e8bc1f,821a4936-2df3-4dc3-a0e4-b82df1086ddb,2026-07-14 14:18:45.221,50,twitch,2026-07-14
296822,e17b0aa1-ff3d-4874-919f-08784a3145e1,d4ce2a45-8c31-426e-9220-6684f206d004,2026-07-14 14:34:45.759,50,twitch,2026-07-14
248630,bcd99cc9-fecd-4630-893e-ed814da73ca1,0df8bc26-9343-428a-a8ae-2b70779c49a2,2026-07-14 14:35:36.754,50,twitch,2026-07-14
143127,6cec7070-494e-4321-8137-e6661fb7b9e5,6313ceac-7806-4d34-aedd-476eed7c853a,2026-07-14 15:49:51.906,50,twitch,2026-07-14

In [209]:
userId = 'fb4e3102-6125-414e-b086-e7f641e38f93'

def get_last_code(x):
    return x.split('-')[-1]

In [210]:
id_novo = []
for i in primeira_transacao['IdCliente']:
    id_novo.append(get_last_code(i))

id_novo

['38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '46723efe2100',
 '46723efe2100',
 '904fcc51e38c',
 '46723efe2100',
 '46723efe2100',
 '46723efe2100',
 '46723efe2100',
 '46723efe2100',
 '07445c6e5943',
 '7b36912f1998',
 '7b36912f1998',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '07445c6e5943',
 '46723efe2100',
 '904fcc51e38c',
 '07445c6e5943',
 '46723efe2100',
 '46723efe2100',
 '46723efe2100',
 '46723efe2100',
 '07445c6e5943',
 '46723efe2100',
 '07445c6e5943',
 '46723efe2100',
 '07445c6e5943',
 '07445c6e5943',
 '46723efe2100',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '46723efe2100',
 '38cf2f4887b3',
 '07445c6e5943',
 'c755e0bc3bd3',
 '46723efe2100',
 '46723efe2100',
 '07445c6e5943',
 '46723efe2100',
 '46723efe2100',
 '07445c6e5943',
 '07445c6e5943',
 '46723efe2100',
 '07445c6e5943',
 '38cf2f4887b3',
 '07445c6e5943',
 '7b36912f1998',
 '07445c6e5943',
 '07445c6e5943',
 '38cf2f4887b3',
 '07445c6e5943',
 '07445c6e5943',
 '07445c6e5943',
 '07445c6e5943',
 '07445c6e5943',
 '07445c6e5943',
 '46723efe2100',
 '46723efe2100',
 '46723efe2100',
 '07445c6e5943',
 '46723efe2100',
 '46723efe2100',
 '46723efe2100',
 '07445c6e5943',
 '592328504897',
 '07445c6e5943',
 '38cf2f4887b3',
 '46723efe2100',
 '07445c6e5943',
 '46723efe2100',
 '07445c6e5943',
 '46723efe2100',
 '07445c6e5943',
 '07445c6e5943',
 '07445c6e5943',
 '46723efe2100',
 '46723efe2100',
 '07445c6e5943',
 'c755e0bc3bd3',
 '07445c6e5943',
 '46723efe2100',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '46723efe2100',
 '38cf2f4887b3',
 '07445c6e5943',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '07445c6e5943',
 '46723efe2100',
 '07445c6e5943',
 '07445c6e5943',
 '07445c6e5943',
 '07445c6e5943',
 '7ed04f00b2e4',
 '07445c6e5943',
 '7ed04f00b2e4',
 '7ed04f00b2e4',
 '7ed04f00b2e4',
 '7ed04f00b2e4',
 '7ed04f00b2e4',
 '8005d2810fc9',
 'd70d1c8d0d97',
 'd70d1c8d0d97',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '33f988c736bc',
 'c60af3148a15',
 '07445c6e5943',
 'c60af3148a15',
 'd70d1c8d0d97',
 '46723efe2100',
 '46723efe2100',
 'd70d1c8d0d97',
 '38cf2f4887b3',
 '46723efe2100',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '07e74ea1574f',
 'c60af3148a15',
 '38cf2f4887b3',
 '07e74ea1574f',
 '38cf2f4887b3',
 '07445c6e5943',
 '38cf2f4887b3',
 '46723efe2100',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '46723efe2100',
 '07e74ea1574f',
 '46723efe2100',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '07445c6e5943',
 '592328504897',
 '07445c6e5943',
 '07e74ea1574f',
 '07445c6e5943',
 'c60af3148a15',
 'c29f9050d938',
 'e181dab54036',
 '38cf2f4887b3',
 '38cf2f4887b3',
 'c755e0bc3bd3',
 'c755e0bc3bd3',
 '38cf2f4887b3',
 'c60af3148a15',
 '04f43dcc6105',
 '8005d2810fc9',
 '15948e0e4108',
 '15948e0e4108',
 '07445c6e5943',
 '07445c6e5943',
 '46723efe2100',
 '07445c6e5943',
 '46723efe2100',
 '46723efe2100',
 'dd08113a0409',
 '46723efe2100',
 '46723efe2100',
 '07445c6e5943',
 '46723efe2100',
 '0a09e5dd5147',
 '46723efe2100',
 'dd08113a0409',
 '07445c6e5943',
 '07445c6e5943',
 '38cf2f4887b3',
 '46723efe2100',
 '355a06554b96',
 '0a09e5dd5147',
 '38cf2f4887b3',
 '19a88acf3401',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 'c755e0bc3bd3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 'c60af3148a15',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '46723efe2100',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '07445c6e5943',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '07445c6e5943',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '46723efe2100',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '46723efe2100',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '355a06554b96',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '46723efe2100',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 'dd08113a0409',
 '38cf2f4887b3',
 'dd08113a0409',
 '38cf2f4887b3',
 'c60af3148a15',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '07445c6e5943',
 '38cf2f4887b3',
 '46723efe2100',
 'c60af3148a15',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 'c29f9050d938',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '46723efe2100',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '06cdc5e80894',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '5a18a3b2f71b',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 'c60af3148a15',
 '07445c6e5943',
 'c60af3148a15',
 'c60af3148a15',
 'c60af3148a15',
 'c60af3148a15',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '46723efe2100',
 '07445c6e5943',
 '07445c6e5943',
 'c60af3148a15',
 '46723efe2100',
 '07445c6e5943',
 '46723efe2100',
 '46723efe2100',
 '07445c6e5943',
 '38cf2f4887b3',
 '07445c6e5943',
 'c60af3148a15',
 '46723efe2100',
 'c60af3148a15',
 'c29f9050d938',
 '46723efe2100',
 '46723efe2100',
 '46723efe2100',
 '07445c6e5943',
 '07445c6e5943',
 'c60af3148a15',
 'c60af3148a15',
 '38cf2f4887b3',
 '3ba49d9b6eab',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '7a3d1737b089',
 '07e74ea1574f',
 '07445c6e5943',
 '07e74ea1574f',
 '07e74ea1574f',
 '38cf2f4887b3',
 '07e74ea1574f',
 '7365c881d2d6',
 '38cf2f4887b3',
 '07e74ea1574f',
 '07445c6e5943',
 '07445c6e5943',
 '46723efe2100',
 '46723efe2100',
 'c60af3148a15',
 'c755e0bc3bd3',
 '46723efe2100',
 '933a6637bfd5',
 '07e74ea1574f',
 'c60af3148a15',
 '46723efe2100',
 '0a09e5dd5147',
 '46723efe2100',
 '46723efe2100',
 'c755e0bc3bd3',
 '46723efe2100',
 'c29f9050d938',
 '38cf2f4887b3',
 '0a09e5dd5147',
 '07445c6e5943',
 '46723efe2100',
 '592328504897',
 '07445c6e5943',
 '46723efe2100',
 'c755e0bc3bd3',
 '15948e0e4108',
 '0a09e5dd5147',
 'c60af3148a15',
 '07445c6e5943',
 'c755e0bc3bd3',
 '46723efe2100',
 'c755e0bc3bd3',
 '0a09e5dd5147',
 '0a09e5dd5147',
 '46723efe2100',
 'c60af3148a15',
 '07445c6e5943',
 '3ba49d9b6eab',
 '0a09e5dd5147',
 '38cf2f4887b3',
 '592328504897',
 '8005d2810fc9',
 '9fc381b682f7',
 'c60af3148a15',
 'c755e0bc3bd3',
 '19a88acf3401',
 '8005d2810fc9',
 'c60af3148a15',
 'c60af3148a15',
 'c60af3148a15',
 'c60af3148a15',
 '07445c6e5943',
 '0a09e5dd5147',
 '07e74ea1574f',
 'c60af3148a15',
 '07e74ea1574f',
 'a03c7b18ce47',
 'a03c7b18ce47',
 '3fb68e054430',
 'a03c7b18ce47',
 'a8d5c28fd4a7',
 '6665e7c2f103',
 'a03c7b18ce47',
 '0a09e5dd5147',
 '6665e7c2f103',
 '6665e7c2f103',
 'a8d5c28fd4a7',
 '0a09e5dd5147',
 '46723efe2100',
 'a03c7b18ce47',
 '38cf2f4887b3',
 '46723efe2100',
 'a03c7b18ce47',
 'a03c7b18ce47',
 'c755e0bc3bd3',
 '0a09e5dd5147',
 '46723efe2100',
 'c60af3148a15',
 '15948e0e4108',
 '0a09e5dd5147',
 '15948e0e4108',
 'd70d1c8d0d97',
 '15948e0e4108',
 'a03c7b18ce47',
 '46723efe2100',
 '46723efe2100',
 'a8d5c28fd4a7',
 '15948e0e4108',
 '07445c6e5943',
 '6665e7c2f103',
 '15948e0e4108',
 'a03c7b18ce47',
 'c60af3148a15',
 'a03c7b18ce47',
 'a8d5c28fd4a7',
 'a8d5c28fd4a7',
 'c29f9050d938',
 '592328504897',
 'c29f9050d938',
 'a03c7b18ce47',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '46723efe2100',
 '46723efe2100',
 '07445c6e5943',
 '07445c6e5943',
 '07445c6e5943',
 '07445c6e5943',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '07445c6e5943',
 '07445c6e5943',
 '46723efe2100',
 '46723efe2100',
 '60bca40e04b9',
 'a67a6cc557c1',
 '95f38c66d6b8',
 '38cf2f4887b3',
 '46723efe2100',
 '95f38c66d6b8',
 '46723efe2100',
 '46723efe2100',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '46723efe2100',
 '46723efe2100',
 'b50e82c16099',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '07445c6e5943',
 'e181dab54036',
 '07445c6e5943',
 '46723efe2100',
 '38cf2f4887b3',
 '46723efe2100',
 'f718ec24f40c',
 '6665e7c2f103',
 '6665e7c2f103',
 '6665e7c2f103',
 '6665e7c2f103',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '46723efe2100',
 '07445c6e5943',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '07445c6e5943',
 '592328504897',
 '46723efe2100',
 '46723efe2100',
 '592328504897',
 'a67a6cc557c1',
 '7b36912f1998',
 '46723efe2100',
 '46723efe2100',
 'a67a6cc557c1',
 '7b36912f1998',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '7b36912f1998',
 '07445c6e5943',
 'c755e0bc3bd3',
 '3ba49d9b6eab',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '46723efe2100',
 '38cf2f4887b3',
 '3ba49d9b6eab',
 '3ba49d9b6eab',
 '07445c6e5943',
 '6665e7c2f103',
 '6665e7c2f103',
 '3ba49d9b6eab',
 '3ba49d9b6eab',
 '07445c6e5943',
 '46723efe2100',
 '38cf2f4887b3',
 '07445c6e5943',
 '07445c6e5943',
 '38cf2f4887b3',
 '07445c6e5943',
 '46723efe2100',
 'c755e0bc3bd3',
 '6665e7c2f103',
 'ad08333c4948',
 '46723efe2100',
 'c755e0bc3bd3',
 '46723efe2100',
 '46723efe2100',
 '7a8031df9c6f',
 'a03c7b18ce47',
 '46723efe2100',
 'c755e0bc3bd3',
 '46723efe2100',
 '38cf2f4887b3',
 '46723efe2100',
 'f718ec24f40c',
 'c755e0bc3bd3',
 'd7766ad093ea',
 'a03c7b18ce47',
 '38cf2f4887b3',
 '46723efe2100',
 '7a8031df9c6f',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 'c755e0bc3bd3',
 '38cf2f4887b3',
 '7a8031df9c6f',
 '5041fe5b943a',
 '46723efe2100',
 '7a8031df9c6f',
 '7a8031df9c6f',
 'ad08333c4948',
 'c755e0bc3bd3',
 'c755e0bc3bd3',
 '46723efe2100',
 '592328504897',
 'f968a50d67d0',
 '19a88acf3401',
 'f968a50d67d0',
 '904fcc51e38c',
 'f968a50d67d0',
 '46723efe2100',
 'c755e0bc3bd3',
 '5041fe5b943a',
 '904fcc51e38c',
 '38cf2f4887b3',
 '38cf2f4887b3',
 'f968a50d67d0',
 '0f9ee3696923',
 'ad08333c4948',
 '46723efe2100',
 'ad08333c4948',
 'bdda6c3a4a6d',
 '6559866fa156',
 'b8418d874f05',
 '023f8ec7ac5d',
 '46723efe2100',
 '46723efe2100',
 '04f43dcc6105',
 'ad08333c4948',
 'f4896942082d',
 'f4896942082d',
 'f4896942082d',
 'f968a50d67d0',
 'f968a50d67d0',
 '46723efe2100',
 'c755e0bc3bd3',
 '46723efe2100',
 'c755e0bc3bd3',
 '38cf2f4887b3',
 '7a8031df9c6f',
 'c755e0bc3bd3',
 '5fd61d7bd709',
 '46723efe2100',
 '7a8031df9c6f',
 '5fd61d7bd709',
 '46723efe2100',
 'c755e0bc3bd3',
 'b451c8674c0e',
 'b451c8674c0e',
 '46723efe2100',
 '7a8031df9c6f',
 '46723efe2100',
 '46723efe2100',
 '5fd61d7bd709',
 'ededf50a9bbb',
 '38cf2f4887b3',
 '46723efe2100',
 '31276c9b9b23',
 '46723efe2100',
 '023f8ec7ac5d',
 '46723efe2100',
 '023f8ec7ac5d',
 'c755e0bc3bd3',
 '38cf2f4887b3',
 '5fd61d7bd709',
 'd7766ad093ea',
 'd7766ad093ea',
 '5fd61d7bd709',
 '5fd61d7bd709',
 '5fd61d7bd709',
 '6665e7c2f103',
 '46723efe2100',
 '6665e7c2f103',
 'bdda6c3a4a6d',
 '6665e7c2f103',
 '46723efe2100',
 'f4896942082d',
 '46723efe2100',
 'a67a6cc557c1',
 '0a09e5dd5147',
 '38cf2f4887b3',
 '38cf2f4887b3',
 'c29f9050d938',
 '5fd61d7bd709',
 '46723efe2100',
 'c60af3148a15',
 '46723efe2100',
 'ac9f99589651',
 'c60af3148a15',
 '023f8ec7ac5d',
 '0eed6b68e5f7',
 '023f8ec7ac5d',
 'db3bac44b2e5',
 '46723efe2100',
 '46723efe2100',
 '46723efe2100',
 '3fb68e054430',
 'ac9f99589651',
 'e181dab54036',
 'c60af3148a15',
 '0a09e5dd5147',
 '46723efe2100',
 '46723efe2100',
 '023f8ec7ac5d',
 'c755e0bc3bd3',
 '38cf2f4887b3',
 '07445c6e5943',
 '07445c6e5943',
 '46723efe2100',
 'f4896942082d',
 '46723efe2100',
 'ac9f99589651',
 '0a09e5dd5147',
 '023f8ec7ac5d',
 'bdda6c3a4a6d',
 '023f8ec7ac5d',
 '46723efe2100',
 '07445c6e5943',
 'ac9f99589651',
 '023f8ec7ac5d',
 '023f8ec7ac5d',
 '38cf2f4887b3',
 '0a09e5dd5147',
 '0a09e5dd5147',
 '023f8ec7ac5d',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '0a09e5dd5147',
 '023f8ec7ac5d',
 '023f8ec7ac5d',
 'bdda6c3a4a6d',
 'bdda6c3a4a6d',
 'bdda6c3a4a6d',
 'a03c7b18ce47',
 'c60af3148a15',
 '023f8ec7ac5d',
 '0a09e5dd5147',
 '023f8ec7ac5d',
 '0a09e5dd5147',
 '0a09e5dd5147',
 '0a09e5dd5147',
 '46723efe2100',
 '46723efe2100',
 '0a09e5dd5147',
 '023f8ec7ac5d',
 '0a09e5dd5147',
 '46723efe2100',
 '0a09e5dd5147',
 '0a09e5dd5147',
 '46723efe2100',
 '0a09e5dd5147',
 'c60af3148a15',
 'c60af3148a15',
 'c60af3148a15',
 '0a09e5dd5147',
 '0a09e5dd5147',
 'c60af3148a15',
 '46723efe2100',
 '38cf2f4887b3',
 '0a09e5dd5147',
 'c60af3148a15',
 'c60af3148a15',
 'c60af3148a15',
 '38cf2f4887b3',
 '0a09e5dd5147',
 '0a09e5dd5147',
 '88e6d917e80e',
 '38cf2f4887b3',
 '38cf2f4887b3',
 'bdda6c3a4a6d',
 '07445c6e5943',
 '07445c6e5943',
 'c60af3148a15',
 'c60af3148a15',
 'c60af3148a15',
 'c60af3148a15',
 'c60af3148a15',
 'a03c7b18ce47',
 'c60af3148a15',
 'a03c7b18ce47',
 'c60af3148a15',
 'a67a6cc557c1',
 'a03c7b18ce47',
 'c60af3148a15',
 '07445c6e5943',
 '07445c6e5943',
 'a03c7b18ce47',
 '07445c6e5943',
 'c755e0bc3bd3',
 'c755e0bc3bd3',
 '07445c6e5943',
 'c755e0bc3bd3',
 'c60af3148a15',
 'c755e0bc3bd3',
 'c755e0bc3bd3',
 'c755e0bc3bd3',
 '31276c9b9b23',
 '38cf2f4887b3',
 '07445c6e5943',
 '31276c9b9b23',
 '07445c6e5943',
 '07445c6e5943',
 '07445c6e5943',
 '07445c6e5943',
 'c755e0bc3bd3',
 '07445c6e5943',
 '07445c6e5943',
 'c755e0bc3bd3',
 '07445c6e5943',
 'c60af3148a15',
 '07445c6e5943',
 'c755e0bc3bd3',
 '07445c6e5943',
 '272447fcafae',
 'c60af3148a15',
 'c60af3148a15',
 'c60af3148a15',
 'c60af3148a15',
 'c60af3148a15',
 '38cf2f4887b3',
 'c60af3148a15',
 'c60af3148a15',
 '38cf2f4887b3',
 'c60af3148a15',
 'c60af3148a15',
 '38cf2f4887b3',
 'd7766ad093ea',
 'c755e0bc3bd3',
 'c29f9050d938',
 'd7766ad093ea',
 'c755e0bc3bd3',
 'c60af3148a15',
 'd7766ad093ea',
 'd7766ad093ea',
 'd7766ad093ea',
 '023f8ec7ac5d',
 'aad6622b1b10',
 'aad6622b1b10',
 'd7766ad093ea',
 'd7766ad093ea',
 'd7766ad093ea',
 'd7766ad093ea',
 'd7766ad093ea',
 '023f8ec7ac5d',
 'd7766ad093ea',
 '023f8ec7ac5d',
 'd7766ad093ea',
 'd7766ad093ea',
 'd7766ad093ea',
 'c60af3148a15',
 'd7766ad093ea',
 'c60af3148a15',
 'd7766ad093ea',
 'c60af3148a15',
 '38cf2f4887b3',
 '46723efe2100',
 'd7766ad093ea',
 '38cf2f4887b3',
 'c29f9050d938',
 'a03c7b18ce47',
 'c60af3148a15',
 '9976bc14b678',
 '08977b39afb2',
 'c755e0bc3bd3',
 'c755e0bc3bd3',
 '592328504897',
 'b005162ff348',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '07445c6e5943',
 '07445c6e5943',
 '46723efe2100',
 '07445c6e5943',
 '07445c6e5943',
 '07445c6e5943',
 '023f8ec7ac5d',
 '07445c6e5943',
 '07445c6e5943',
 '46723efe2100',
 '46723efe2100',
 '07445c6e5943',
 'c755e0bc3bd3',
 '023f8ec7ac5d',
 '46723efe2100',
 '023f8ec7ac5d',
 'd7766ad093ea',
 '023f8ec7ac5d',
 '38cf2f4887b3',
 '38cf2f4887b3',
 'd7766ad093ea',
 '43c8e8eef6ef',
 '38cf2f4887b3',
 '46723efe2100',
 '46723efe2100',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '592328504897',
 '07445c6e5943',
 '38cf2f4887b3',
 '46723efe2100',
 '38cf2f4887b3',
 '07445c6e5943',
 '38cf2f4887b3',
 '43c8e8eef6ef',
 '46723efe2100',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '07445c6e5943',
 '07445c6e5943',
 '07445c6e5943',
 '904fcc51e38c',
 '46723efe2100',
 '38cf2f4887b3',
 'c755e0bc3bd3',
 '38cf2f4887b3',
 '46723efe2100',
 '07445c6e5943',
 '904fcc51e38c',
 '07445c6e5943',
 '904fcc51e38c',
 '592328504897',
 '46723efe2100',
 '07445c6e5943',
 'a67a6cc557c1',
 '904fcc51e38c',
 'b8418d874f05',
 '38cf2f4887b3',
 '904fcc51e38c',
 'd7766ad093ea',
 'd7766ad093ea',
 '07445c6e5943',
 '933a6637bfd5',
 '46723efe2100',
 'a67a6cc557c1',
 '07445c6e5943',
 '19a88acf3401',
 '46723efe2100',
 '07445c6e5943',
 '46723efe2100',
 '07445c6e5943',
 '46723efe2100',
 'a67a6cc557c1',
 '07445c6e5943',
 '07445c6e5943',
 '46723efe2100',
 '38cf2f4887b3',
 '07445c6e5943',
 '07445c6e5943',
 'c755e0bc3bd3',
 '933a6637bfd5',
 '07445c6e5943',
 '38cf2f4887b3',
 '46723efe2100',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '07445c6e5943',
 '07445c6e5943',
 '38cf2f4887b3',
 '46723efe2100',
 '646d0f6be4f6',
 '07445c6e5943',
 '43c8e8eef6ef',
 '904fcc51e38c',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '38cf2f4887b3',
 'bdda6c3a4a6d',
 'a67a6cc557c1',
 '46723efe2100',
 '5a18a3b2f71b',
 '46723efe2100',
 '646d0f6be4f6',
 '904fcc51e38c',
 '46723efe2100',
 '02080a55af96',
 'bdda6c3a4a6d',
 'bdda6c3a4a6d',
 '38cf2f4887b3',
 '46723efe2100',
 '02080a55af96',
 '43c8e8eef6ef',
 'bdda6c3a4a6d',
 '904fcc51e38c',
 '592328504897',
 '46723efe2100',
 '5a18a3b2f71b',
 '38cf2f4887b3',
 '38cf2f4887b3',
 '46723efe2100',
 '43c8e8eef6ef',
 '38cf2f4887b3',
 '8cedd9dae64e',
 '38cf2f4887b3',
 ...]

In [211]:
primeira_transacao['IdCliente'].apply(get_last_code)

330916    38cf2f4887b3
4605      38cf2f4887b3
21302     38cf2f4887b3
4828      38cf2f4887b3
305766    38cf2f4887b3
              ...
143127    476eed7c853a
193551    476eed7c853a
213273    1bcb4db2adaa
181504    1bcb4db2adaa
312832    57d8fa0ed7e1
Name: IdCliente, Length: 337074, dtype: str

In [216]:
print(series_idades.mean())
print(series_idades.median())
print(series_idades.mode())
print(series_idades.max())
print(series_idades.min())
series_idades.describe()

32.0
31.0
0    23
dtype: int64
43
22

count    15.000000
mean     32.000000
std       6.897204
min      22.000000
25%      27.500000
50%      31.000000
75%      38.000000
max      43.000000
dtype: float64

In [219]:
clientes['flTwitch'].mean()

np.float64(0.7299270072992701)

In [225]:
filtro = clientes.dtypes == 'str'
num_columns = clientes.dtypes[~filtro].index.tolist()

In [226]:
clientes[num_columns].mean()

flEmail                              0.074239
flTwitch                             0.729927
flYouTube                            0.058394
flBlueSky                                 0.0
flInstagram                               0.0
qtdePontos                         440.201531
DtCriacao          2025-03-21 18:01:05.831564
Email_ou_Twitch                      0.804166
Redes_Sociais                         0.86256
Todas_Social                              0.0
logPontos                            3.451927
dtype: object

In [227]:
clientes[num_columns].describe()

,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,Email_ou_Twitch,Redes_Sociais,Todas_Social,logPontos
count,5617.000000,5617.000000,5617.000000,5617.0,5617.0,5617.000000,5617,5617.000000,5617.000000,5617.0,5616.000000
mean,0.074239,0.729927,0.058394,0.0,0.0,440.201531,2025-03-21 18:01:05.831564,0.804166,0.862560,0.0,3.451927
min,0.000000,0.000000,0.000000,0.0,0.0,-10.000000,2024-02-01 09:00:00,0.000000,0.000000,0.0,0.000000
25%,0.000000,0.000000,0.000000,0.0,0.0,0.000000,2024-02-01 09:00:00,0.000000,0.000000,0.0,0.000000
50%,0.000000,1.000000,0.000000,0.0,0.0,51.000000,2025-06-25 13:46:27.163000,1.000000,1.000000,0.0,3.951244
75%,0.000000,1.000000,0.000000,0.0,0.0,283.000000,2025-10-29 01:11:59.170000,1.000000,1.000000,0.0,5.650729
max,1.000000,1.000000,1.000000,0.0,0.0,32860.000000,2026-07-15 01:39:43.577000,2.000000,3.000000,0.0,10.400042
std,0.262183,0.444037,0.234508,0.0,0.0,1332.417690,NaN,0.534524,0.692848,0.0,2.815050