Este notebook compreende os estudos práticos da biblioteca pandas para dados tabulares e manipulação de dados

Todo os estudos foram feitos com base no curso Pandas 2025 do canal do YouTube Téo Me Why.

Segue abaixo o link para a playlist e para a base de dados utilizada nos estudos:

    Curso: https://youtube.com/playlist?list=PLvlkVRRKOYFQHnDhjTmXLEz3HU5WTgOcF&si=iI3RDed5BIWAZmDZ
    Dataset: https://www.kaggle.com/datasets/teocalvo/teomewhy-loyalty-system

In [2]:
import pandas as pd

In [11]:
idade = [31, 28, 40, 37, 35, 23, 43, 39, 22, 23, 30, 29, 41, 27, 32]

series_idades = pd.Series(idade)
series_idades

0     31
1     28
2     40
3     37
4     35
5     23
6     43
7     39
8     22
9     23
10    30
11    29
12    41
13    27
14    32
dtype: int64

In [ ]:

media_idades = series_idades.mean()
summary_idades = series_idades.describe()

summary_idades

32.0

count    15.000000
mean     32.000000
std       6.897204
min      22.000000
25%      27.500000
50%      31.000000
75%      38.000000
max      43.000000
dtype: float64

In [22]:
# cada elemento dentro da Serie se associa a um índice, semelhante a uma chave de dicionário

print(series_idades[0]) # acessando elemento pelo seu índice

series_idades = series_idades.sort_values() # ordenando os valores da Serie
print(series_idades)

print(series_idades[0]) 
# ao tentar acessar novamente o elemento 0 após a ordenação, 
# o valor imprimido é o mesmo, já que a estrutura se comporta como chave:valor

print(series_idades.iloc[0]) # o iloc permite acessar o elemento a partir da posição dele dentro da Serie, que passa a se comportar como lista

31
8     22
5     23
9     23
13    27
1     28
11    29
10    30
0     31
14    32
4     35
3     37
7     39
2     40
12    41
6     43
dtype: int64
31
22

In [25]:
indexs = ["Mario", "Remi", "Ana", "Jonatas", "Olga", "Helena", "Ana", "Bia", 
          "Beto", "Pedro", "Ronaldo", "Vinicius", "Fernando", "Katia", "Carlos"]

# os índices das Series não precisam ser necessariamente númericos, nem únicos

series_idades = pd.Series(idade, index=indexs)
series_idades

series_idades['Ana'] # acessando o elemento no índice(chave) 'Ana', como possui mais de um, ele retornará todos que encontrar

Ana    40
Ana    43
dtype: int64

Dataframes

In [28]:
idade = [31, 28, 40, 37, 35, 23, 43, 39, 22, 23, 30, 29, 41, 27, 32]
nomes = ["Mario", "Remi", "Ana", "Jonatas", "Olga", "Helena", "Ana", "Bia", 
          "Beto", "Pedro", "Ronaldo", "Vinicius", "Fernando", "Katia", "Carlos"]

series_idades = pd.Series(idade)

df = pd.DataFrame() # cria um dataframe vazio

df["Idades"] = series_idades # adicionando uma Serie como uma nova coluna do dataframe e nomendo-a
df["Nomes"] = nomes # mesmo processo porém agora com uma lista
df

    Idades     Nomes
0       31     Mario
1       28      Remi
2       40       Ana
3       37   Jonatas
4       35      Olga
5       23    Helena
6       43       Ana
7       39       Bia
8       22      Beto
9       23     Pedro
10      30   Ronaldo
11      29  Vinicius
12      41  Fernando
13      27     Katia
14      32    Carlos

In [ ]:
print(df["Nomes"]) # Acessar uma coluna dentro do DataFrame a retorna como uma Serie

print(df.iloc[0]) # Acessa uma linha dentro do DataFrame e a retorna como uma Serie

# ao acessar um elemento dentro de um dataframe por coluna, o índice da Serie retornada será o mesmo do dataframe (0)
# ao acessar um elemento dentro de um dataframe por linha, o índice da Serie retornada será o nome das colunas (Idades, Nomes)

0        Mario
1         Remi
2          Ana
3      Jonatas
4         Olga
5       Helena
6          Ana
7          Bia
8         Beto
9        Pedro
10     Ronaldo
11    Vinicius
12    Fernando
13       Katia
14      Carlos
Name: Nomes, dtype: str
Idades       31
Nomes     Mario
Name: 0, dtype: object

In [34]:
# Ao acessar um elemento, seja por linha ou coluna, e obter uma Serie como resposta, é possível navegar dentro dela como uma Serie de fato

print(df.iloc[-1]["Nomes"]) # Acessando a linha do último elemento do DataFrame e obtendo seu nome
print(df.iloc[-1]["Idades"]) # Acessando a linha do último elemento do DataFrame e obtendo sua idade

Carlos
32

Importando dados

In [4]:
df = pd.read_csv('../data/clientes.csv')
df

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551
...,...,...,...,...,...,...,...,...,...
5612,ff5d2399-6b53-49f0-b41e-fdaaa0da172a,0,1,0,0,0,2021,2025-08-25 13:09:12.556,2026-01-30 14:43:50.139
5613,ff8d55dc-64fa-40de-992a-04a4155f5634,0,1,0,0,0,0,2025-07-12 13:50:37.959,2025-07-12 13:50:37.959
5614,ffcf3b9c-8cc8-4fca-a93a-e01a6fd830f0,1,1,1,0,0,0,2026-05-06 14:42:42.170,2026-05-06 14:44:23.800
5615,fff7862d-4b2c-4140-a4c5-509b48ed31b4,0,1,0,0,0,1000,2025-11-12 01:01:58.698,2025-11-12 01:02:16.561
5616,fff940d1-0786-4ee5-a75a-3bbda4e50f7a,0,1,0,0,0,0,2026-04-29 13:33:15.703,2026-04-29 13:33:15.703

In [11]:
df_2 = pd.read_csv('../data/transacao_produto.csv', sep=';')
df_2

#o dataset original está com separador ; e agora estou salvando o dataset em outro local com separador ,
df_2.to_csv('transacao_comma.csv', sep=',', index=False)